apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tomas-rojo/argocd-gitops.git
    targetRevision: HEAD
    path: infra-appsets
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 30s