apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bmk-infra
  namespace: bmk
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: bmk
  source:
    repoURL: https://github.com/tomas-rojo/argocd-gitops.git
    targetRevision: HEAD
    path: infra-apps/benchmark-infra
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true