apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-infra-appset
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - service: envoy-gateway
            chartVersion: "v1.4.1"
            chart: gateway-helm
            repoUrl: docker.io/envoyproxy
            namespace: gateway
          - service: redis
            chartVersion: "21.0.0"
            chart: redis
            repoUrl: https://charts.bitnami.com/bitnami
            namespace: dev
          - service: github-runners
            chartVersion: "0.23.7"
            chart: actions-runner-controller
            repoUrl: https://actions-runner-controller.github.io/actions-runner-controller
            namespace: default
          - service: cert-manager
            chartVersion: "v1.12.0"
            chart: cert-manager
            repoUrl: https://charts.jetstack.io
            namespace: cert-manager
          - service: envoy-gateway-config
            chartVersion: "0.1.0"
            chart: envoy-gateway
            repoUrl: ghcr.io/tomas-rojo
            namespace: default
  template:
    metadata:
      name: "dev-{{ .service }}"
    spec:
      source:
        repoURL: "{{ .repoUrl }}"
        targetRevision: "{{ .chartVersion }}"
        chart: "{{ .chart }}"
        helm:
          releaseName: "{{ .service }}"
      destination:
        name: in-cluster
        namespace: "{{ .namespace }}"
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
