apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bmk-appset
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - service: inventory-service
            secrets: false
            chartVersion: '0.1.0'
          - service: ecolabel-service
            secrets: false
            chartVersion: '0.1.1'
  template:
    metadata:
      name: "bmk-{{ .service }}"
    spec:
      destination:
        name: in-cluster
        namespace: bmk
      project: bmk
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
  templatePatch: |
    spec:
      sources:
        - repoURL: ghcr.io/tomas-rojo
          targetRevision: {{.chartVersion}}
          chart: '{{.service}}'
          helm:
            releaseName: '{{.service}}'
            {{ if .secrets }}
            valueFiles:
              - $values/.chart/values.bmk.yaml
              - $values/.chart/secrets.bmk.yaml
            {{ else }}
            valueFiles:
              - $values/.chart/values.bmk.yaml
            {{ end }}
        - repoURL: https://github.com/trojocerqlar/{{.service}}
          targetRevision: main
          ref: values